# Project Information
site_name: FlyByWire Simulations Guides
site_url: https://docs.flybywiresim.com
# repo allows for linking main repo to docs
# Uncomment to use
repo_url: https://github.com/flybywiresim/a32nx/
repo_name: flybywiresim/a32nx
edit_uri: "" #removes edit button and icon

# Navigation
# Section Containers are defined by `- Section Name:`
# These should have NO filename.md next to them
# Nestle all pages under neath sections as seen below:
nav:
 - Home: index.md
 - Getting Started:
   - Installation: start/installation.md
   - Starting the plane: start/first-steps.md
   - Common Questions: start/faq.md
 - Airliner Flying Guide:
   - Overview: airliner-flying-guide/airliner-flying.md
   - Types of Approaches: airliner-flying-guide/approaches.md
   - Navigation: airliner-flying-guide/navigation.md
   - Understanding Altitude References: airliner-flying-guide/altitude-refs.md
   - METARs/TAFs/ATIS: airliner-flying-guide/weather.md
 - SDK Overview:
   - Docker & Building: sdk/docker.md
   - HTML/JS Gauges: sdk/html-gauges.md
   - WASM Gauges: sdk/wasm-gauges.md
   - XML & RNP: sdk/xml-rnp.md
   - Sounds: sdk/sounds.md
   - Modeling: sdk/modeling.md
   - Texturing: sdk/texturing.md
 - Common Development:
   - Blender Plugin: common-dev/blender.md
   - EFB: common-dev/efb.md
   - Installer: common-dev/installer.md
   - Rust SDK: common-dev/msfs-rs.md
   - Web API: common-dev/web-api.md
 - A32NX Development:
   - Overview: a32nx-dev/overview.md
   - HTML/JS Code: a32nx-dev/html.md
   - Local SimVars: a32nx-dev/simvars.md
   - XML ModelBehaviors: a32nx-dev/xml.md
   - React Overhaul: a32nx-dev/react.md
 - Donate: donate.md


# Configuration
theme:
  name: material
# Theme Overhaul configruation. Use with caution.
# Uncomment custom_dir requires additional setup.
  #custom_dir: overrides
  logo: assets/images/FBW-Square-White.png
  palette:
    scheme: slate
  features:
   - navigation.tabs
   - navigation.instant
  favicon: assets/images/FBW-tail.png

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: date

# Styling Front-end
extra_css:
  - stylesheets/extra.css

# Extra Functions / Customizations
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FlyByWireSimulations/
      name: FlyByWire Simulations on Facebook

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list
  - pymdownx.tabbed #content tabs
  - pymdownx.details # Additional features to admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji: #Allows emjoy style inline embeds for icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
