# Project Information
site_name: FlyByWire Simulations Documentation
site_url: https://docs.flybywiresim.com/
site_description: Comprehensive documentation for FlyByWire Simulations
# repo allows for linking main repo to docs
# Uncomment to use
repo_url: https://github.com/flybywiresim/aircraft/
repo_name: flybywiresim/aircraft
edit_uri: "" #removes edit button and icon
copyright: Powered by <a href="https://vercel.com/?utm_source=flybywiresim&utm_campaign=oss" target="_blank">
  <img src="/assets/images/vercel-logotype-light.svg" alt="Vercel Logo"></a>

# Configuration
theme:
  name: material
  # Theme Overhaul configuration. Use with caution.
  # Uncommenting custom_dir requires additional setup.
  custom_dir: overrides
  logo: assets/images/FBW-Tail.png
  font:
    text: Inter
  palette:
    scheme: slate
    primary: custom
  features:
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    # Removed this feature again as it's breaking TOC navigation on reported-issues.md
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/images/FBW-Tail.png

# Plugins
plugins:
  search:
    lang: en
  # Comment out the plugin below if building docs without an internet connection.
  external-markdown: {}
  awesome-pages: {}
  tags: {}
  git-revision-date-localized:
    type: date
  mkdocs-video:
    mark: "video-embed"
  redirects:
      redirect_maps:
        # Folder: /start/
        'start/fbw-versions.md': 'fbw-a32nx/fbw-versions.md'
        'start/installation.md': 'fbw-a32nx/installation.md'
        'start/support.md': 'fbw-a32nx/support/index.md'
        'start/reported-issues.md': 'fbw-a32nx/support/reported-issues.md'
        'start/autopilot-fbw.md': 'fbw-a32nx/feature-guides/autopilot-fbw.md'
        # Commented out in case we want to use this in the future
#        'start/exp.md': 'fbw-a32nx/support/exp.md'
        # Folder: /beginner-guide/
        'beginner-guide/overview.md': 'pilots-corner/beginner-guide/overview.md'
        # Folder: /airliner-flying-guide/
        'airliner-flying-guide/overview.md': 'pilots-corner/airliner-flying-guide/overview.md'
        # Folder: /development-projects/
        'development-projects/overview.md': 'dev-corner/dev-guide/index.md'
        'development-projects/website.md': 'dev-corner/development-projects/website.md'
        # Folder: /a32nx-devs/
        'a32nx-dev/overview.md': 'dev-corner/dev-guide/index.md'
        'a32nx-dev/texture-changes.md': 'dev-corner/texture-changes.md'
        # TEMP redirects
      # A.FLOOR
        'fbw-a32nx/feature-guides/afloor.md': 'pilots-corner/advanced-guides/protections/afloor.md'
        # Fix Info
        'fbw-a32nx/feature-guides/fixinfo.md': 'pilots-corner/advanced-guides/flight-planning/fixinfo.md'
        # A32NX API
        'pilots-corner/a32nx-briefing/a32nx_api.md': 'fbw-a32nx/a32nx-api/a32nx-flightdeck-api.md'

        # additional redirects:
        'fbw-a32nx/feature-guides/throttle-calibration.md': 'fbw-a32nx/feature-guides/flypados3/throttle-calibration.md'
        # Convenience redirects:
        'beginner-guide.md': 'pilots-corner/beginner-guide/overview.md'
        'installation.md': 'fbw-a32nx/installation.md'
        'throttle.md': 'fbw-a32nx/feature-guides/flypados3/throttle-calibration.md'
        'reported-issues.md': 'fbw-a32nx/support/reported-issues.md'
        'support.md': 'fbw-a32nx/support/index.md'
        'discord-bot.md': 'dev-corner/development-projects/discord-bot.md'
        'airframe.md': 'https://docs.flybywiresim.com/fbw-a32nx/installation/#simbrief-airframe'
        'fdr.md': 'https://docs.flybywiresim.com/fbw-a32nx/support/#fdr-files'
        'flypad-performance.md': 'fbw-a32nx/feature-guides/flypados3/performance.md'
        # Commented out in case we want to use this in the future
        #        'exp.md': 'fbw-a32nx/support/exp.md'
        'vnav.md': 'pilots-corner/advanced-guides/flight-guidance/vertical-guidance/overview.md'
        # Release Notes Permalink
        'latest-release.md': 'release-notes/v0111.md'
        'latest-installer-release.md': 'release-notes/installer/v330.md'
        # ########################################
        # Needed for URL within the A32NX aircraft
        # ########################################
        'telex.md': 'https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/settings/#atsuaoc'
  glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - skip-lightbox
    auto_caption: false
    caption_position: bottom

extra_javascript:
  - javascripts/gif-play.js

# Styling Front-end
extra_css:
  - stylesheets/extra.css
  - stylesheets/admonitions.css
  - stylesheets/navigation.css
  - stylesheets/gif-anim-style.css

# Javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extra Functions / Customizations
extra:
  status:
    new: Recently Updated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flybywiresim
      name: FlyByWire Simulations on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FlyByWireSim
      name: FlyByWire Simulations on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FlyByWireSimulations
      name: FlyByWire Simulations on Facebook
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/flybywire
      name: FlyByWire Simulations on Discord
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/flybywiresimulations
      name: FlyByWire Simulations on Twitch
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FlyByWireSim
      name: FlyByWire Simulations on Youtube

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  meta: {} # Add front matter to a document
  admonition: {} # Makes things pretty
  pymdownx.superfences: {} # Nestled code
  pymdownx.arithmatex: # Math and equations
    generic: true
  attr_list: {} # Add HTML attributes and CSS classes to Markdown elements
  pymdownx.tabbed: # Content tabs
    alternate_style: true
  pymdownx.details: {} # Additional features to admonition
  pymdownx.caret: {} # Formatting Extension
  pymdownx.critic: {} # Alternate Formatting Extension
  pymdownx.mark: {} # Formatting Extension
  pymdownx.tilde: {} # Formatting Extension
  pymdownx.keys: {} # Visual keyboard keys extension
  pymdownx.snippets: 
    auto_append: 
    - includes/abbreviations.md
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.emoji: # Allows emoji style inline embeds for icons
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  md_in_html: {} # Allows markdown to be used in HTML
  abbr: {} # Adds abbreviations
