# Project Information
site_name: FlyByWire Simulations Documentation
site_url: https://docs.flybywiresim.com/
# repo allows for linking main repo to docs
# Uncomment to use
repo_url: https://github.com/flybywiresim/a32nx/
repo_name: flybywiresim/a32nx
edit_uri: "" #removes edit button and icon

# Configuration
theme:
  name: material
  # Theme Overhaul configuration. Use with caution.
  # Uncommenting custom_dir requires additional setup.
  custom_dir: overrides
  logo: assets/images/FBW-Tail.png
  font:
    text: Nunito Sans
  palette:
    scheme: slate
  features:
    - navigation.tabs
    # Temporarily deactivated to provide support for Discord browser + anchor links
    # - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/images/FBW-Tail.png

# Plugins
plugins:
  - search:
      lang: en
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:
        # Folder: /start/
        'start/fbw-versions.md': 'fbw-a32nx/fbw-versions.md'
        'start/installation.md': 'fbw-a32nx/installation.md'
        'start/support.md': 'fbw-a32nx/support/index.md'
        'start/convert-liveries.md': 'fbw-a32nx/liveries.md'
        'start/reported-issues.md': 'fbw-a32nx/support/reported-issues.md'
        'start/performance-tips.md': 'fbw-a32nx/support/performance-tips.md'
        'start/faq.md': 'fbw-a32nx/support/faq.md'
        'start/mcdu-keyboard.md': 'fbw-a32nx/feature-guides/mcdu-keyboard.md'
        'start/throttle-calibration.md': 'fbw-a32nx/feature-guides/flyPad/throttle-calibration.md'
        'start/autopilot-fbw.md': 'fbw-a32nx/feature-guides/autopilot-fbw.md'
        'start/exp.md': 'fbw-a32nx/support/exp.md'
        # Folder: /beginner-guide/
        'beginner-guide/overview.md': 'pilots-corner/beginner-guide/overview.md'
        # Folder: /airliner-flying-guide/
        'airliner-flying-guide/overview.md': 'pilots-corner/airliner-flying-guide/overview.md'
        # Folder: /development-projects/
        'development-projects/overview.md': 'dev-corner/development-practices.md'
        'development-projects/website.md': 'dev-corner/development-projects/website.md'
        # Folder: /a32nx-devs/
        'a32nx-dev/overview.md': 'dev-corner/development-guide.md'
        'a32nx-dev/texture-changes.md': 'dev-corner/texture-changes.md'
        # additional redirects:
        'fbw-a32nx/feature-guides/throttle-calibration.md': 'fbw-a32nx/feature-guides/flyPad/throttle-calibration.md'


        # 'old.md': 'file.md'
        # 'some_file.md': 'http://external.url.com/foobar'

# Styling Front-end
extra_css:
  - stylesheets/extra.css
  - stylesheets/EFB-interactive.css

# Extra Functions / Customizations
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flybywiresim
      name: FlyByWire Simulations on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FlyByWireSim
      name: FlyByWire Simulations on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FlyByWireSimulations
      name: FlyByWire Simulations on Facebook
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/flybywire
      name: FlyByWire Simulations on Discord
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/flybywiresimulations
      name: FlyByWire Simulations on Twitch
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/flybywiresimulations
      name: FlyByWire Simulations on Youtube

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  - meta # Add front matter to a document
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list # Add HTML attributes and CSS classes to Markdown elements
  - pymdownx.tabbed # Content tabs
  - pymdownx.details # Additional features to admonition
  - pymdownx.caret # Formatting Extension
  - pymdownx.mark # Formatting Extension
  - pymdownx.tilde # Formatting Extension
  - pymdownx.keys # Visual keyboard keys extension
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji: # Allows emoji style inline embeds for icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
